#!/bin/bash

sep="   |   "
bar=""

if [ -f "$HOME/todo.md" ]; then
   todos_done=$(grep -- '- \[x\]' $HOME/todo.md | wc -l)
   todos_all=$(grep -- '- \[.\]' $HOME/todo.md | wc -l)
   bar+=" $todos_done/$todos_all$sep"
fi

disk=$(df -h / | tail -n 1 | awk '{print$3}')
bar+=" $disk$sep"

if [ -f "/sys/class/power_supply/BAT1/capacity" ]; then
   bat=$(cat /sys/class/power_supply/BAT1/capacity)
   bat_icons=(    )
   bat_icon=${bat_icons[(((bat - 1) / 20))]}
   bat_status=$(cat /sys/class/power_supply/BAT1/status)

   if [[ "$bat_status" == "Charging" ]]; then
      bat_icon=""
   fi

   bar+="$bat_icon $bat$sep"
fi

date=$(date +'%a %d %b %Y')
bar+=" $date$sep"

time=$(date +'%H:%M')
bar+=" $time  "

echo "$bar"
