#!/bin/bash

bat=$(cat /sys/class/power_supply/BAT1/capacity)
disk=$(df -h / | tail -n 1 | awk '{print$3}')
date=$(date +'%a %d %b %Y')
time=$(date +'%H:%M')

bat_icons=(    )
bat_icon=${bat_icons[(((bat - 1) / 20))]}
bat_status=$(cat /sys/class/power_supply/BAT1/status)

if [[ "$status" == "Charging" ]]; then
   bat_icon=""
fi

echo " $disk   |   $bat_icon $bat%   |    $date   |    $time  "
